services:
  app:
    build: .
    container_name: app
    image: template-go
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - template-postgres:/data
    environment:
      POSTGRES_PASSWORD: 123123123
      POSTGRES_USER: shuneo
      POSTGRES_DB: database
      PGDATA: /data
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass 123123123
    volumes:
      - template-redis:/data

volumes:
  template-redis:
  template-postgres:

